project: normastars
log_level: info
log_mode: text
enable_metric: true
env: dev
http_server:
    enable: true
    disable_req_log: false
    configs:
        - name: server
          port: :8080
        - name: metrics
          port: :9090
mysql:
    enable: true
    disable_req_log: true
    configs:
        - name: user
          enable: true
          enable_auto_migrate: true
          host: 127.0.0.1:3309
          database: user
          user: root
          password: root
          slow_threshold_sec: 3
redis:
    enable: true
    disable_req_log: true
    configs:
        - name: user
          enable: true
          host: 127.0.0.1:6380
          poolsize: 0
          password: ""
          db: 0